@baseUrl = http://localhost:6543

### get ll 
GET {{baseUrl}}/api/v1/product/

### get by id
GET {{baseUrl}}/api/v1/product/?productId=27

### create product
POST {{baseUrl}}/api/v1/product/

{
    "name": "product 1",
    "price": 1000
}

### update product
PUT {{baseUrl}}/api/v1/product/

{
    "id": 1,
    "name": "Bagaya Kyaung",
    "price": 10000.0,
    "description": "Product 1 description",
    "image_url": "No image",
    "stock": 10
}

### delete product
DELETE  {{baseUrl}}/api/v1/product/

{
    "id": 14
}

### get price products
POST {{baseUrl}}/api/v1/product/sum-price

{
    "id": [30, 32, 33]
}