# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"i\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x11\n\timage_url\x18\x05 \x01(\t\x12\r\n\x05stock\x18\x06 \x01(\x05\"K\n\x13ProductListResponse\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.products.Product\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12ProductListRequest\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"F\n\x0fProductResponse\x12\"\n\x07product\x18\x01 \x01(\x0b\x32\x11.products.Product\x12\x0f\n\x07message\x18\x02 \x01(\t\"j\n\x14ProductCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\r\n\x05stock\x18\x05 \x01(\x05\"v\n\x14ProductUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x11\n\timage_url\x18\x06 \x01(\t\"\"\n\x14ProductDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"(\n\x15ProductDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8d\x03\n\x08Products\x12\x43\n\nGetProduct\x12\x18.products.ProductRequest\x1a\x19.products.ProductResponse\"\x00\x12L\n\x0bGetProducts\x12\x1c.products.ProductListRequest\x1a\x1d.products.ProductListResponse\"\x00\x12L\n\rCreateProduct\x12\x1e.products.ProductCreateRequest\x1a\x19.products.ProductResponse\"\x00\x12L\n\rUpdateProduct\x12\x1e.products.ProductUpdateRequest\x1a\x19.products.ProductResponse\"\x00\x12R\n\rDeleteProduct\x12\x1e.products.ProductDeleteRequest\x1a\x1f.products.ProductDeleteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=28
  _globals['_PRODUCT']._serialized_end=133
  _globals['_PRODUCTLISTRESPONSE']._serialized_start=135
  _globals['_PRODUCTLISTRESPONSE']._serialized_end=210
  _globals['_PRODUCTLISTREQUEST']._serialized_start=212
  _globals['_PRODUCTLISTREQUEST']._serialized_end=232
  _globals['_PRODUCTREQUEST']._serialized_start=234
  _globals['_PRODUCTREQUEST']._serialized_end=262
  _globals['_PRODUCTRESPONSE']._serialized_start=264
  _globals['_PRODUCTRESPONSE']._serialized_end=334
  _globals['_PRODUCTCREATEREQUEST']._serialized_start=336
  _globals['_PRODUCTCREATEREQUEST']._serialized_end=442
  _globals['_PRODUCTUPDATEREQUEST']._serialized_start=444
  _globals['_PRODUCTUPDATEREQUEST']._serialized_end=562
  _globals['_PRODUCTDELETEREQUEST']._serialized_start=564
  _globals['_PRODUCTDELETEREQUEST']._serialized_end=598
  _globals['_PRODUCTDELETERESPONSE']._serialized_start=600
  _globals['_PRODUCTDELETERESPONSE']._serialized_end=640
  _globals['_PRODUCTS']._serialized_start=643
  _globals['_PRODUCTS']._serialized_end=1040
# @@protoc_insertion_point(module_scope)
